services:
  - type: web
    name: backend-hex-arch-8
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: singapore # หรือ oregon, frankfurt
    healthCheckPath: /health